name: Update LeetCode Stats
on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight (UTC)
  workflow_dispatch:  # Allows manual triggering
jobs:
  update:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
      - uses: JeremyTsaii/leetcode-stats@latest
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          leetcode_username: "Pavithran1403"  # Replace with your LeetCode username
